name: Lint

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Linter
        uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "."
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Flake Linter
        uses: py-actions/flake8@v2
